=== yilinliumay/FootBallStrategy/src/Data/games.dtd
<!ELEMENT Games (Game*) >
        <!ELEMENT Game (players, result) >
        <!ATTLIST Game id CDATA #REQUIRED>
        <!ELEMENT players (player*)>
        <!ELEMENT player (attack*,defense*,goal,position,discipline) >
        <!--the success rate of dribble, pitching....-->
        <!ELEMENT attack (dribble,pitching,cross,shooting,header,freeKick) >
        <!ELEMENT dribble (#PCDATA)>
        <!ELEMENT pitching (#PCDATA)>
        <!ELEMENT cross (#PCDATA)>
        <!ELEMENT shooting (#PCDATA)>
        <!ELEMENT header (#PCDATA)>
        <!ELEMENT freeKick (#PCDATA)>
        <!--the success rate of broken,interception....-->
        <!ELEMENT defense (broken,interception,clearance,forcedGrab,headerClearance,GoalkeeperRescue) >
        <!ELEMENT broken (#PCDATA)>
        <!ELEMENT interception (#PCDATA)>
        <!ELEMENT clearance (#PCDATA)>
        <!ELEMENT forcedGrab (#PCDATA)>
        <!ELEMENT headerClearance (#PCDATA)>
        <!ELEMENT GoalkeeperRescue (#PCDATA)>
        <!--the number of red and yellow cards he got -->
        <!ELEMENT discipline (red,yellow)>
        <!ELEMENT red (#PCDATA)>
        <!ELEMENT yellow (#PCDATA)>
        <!ELEMENT goal (#PCDATA)>
        <!ELEMENT position (#PCDATA)>
        <!ATTLIST player ID CDATA #REQUIRED>
        <!ELEMENT result (#PCDATA)>

=== yilinliumay/FootBallStrategy/src/Data/games.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Games SYSTEM "/Users/mayliu/IdeaProjects/FootBallStrategy/src/Data/games.dtd">
<Games>
    <Game id="1">
        <players>
            <player ID="LM">
                <attack>
                    <dribble>0.6</dribble>
                    <pitching>1</pitching>
                    <cross>0.5</cross>
                    <shooting>0.8</shooting>
                    <header>1</header>
                    <freeKick>0.5</freeKick>
                </attack>
                <defense>
                    <broken>0.2</broken>
                    <interception>0.1</interception>
                    <clearance>0.5</clearance>
                    <forcedGrab>0.4</forcedGrab>
                    <headerClearance>0.5</headerClearance>
                    <GoalkeeperRescue>0</GoalkeeperRescue>
                </defense>
                <goal>1</goal>
                <position>Forward</position>
                <discipline>
                    <red>0</red>
                    <yellow>1</yellow>
                </discipline>
            </player>
            <player ID="LS">
                <attack>
                    <dribble>0.7</dribble>
                    <pitching>0.4</pitching>
                    <cross>0.6</cross>
                    <shooting>0.5</shooting>
                    <header>0.5</header>
                    <freeKick>1</freeKick>
                </attack>
                <defense>
                    <broken>0.4</broken>
                    <interception>0.2</interception>
                    <clearance>0</clearance>
                    <forcedGrab>0.3</forcedGrab>
                    <headerClearance>0.3</headerClearance>
                    <GoalkeeperRescue>0</GoalkeeperRescue>
                </defense>
                <goal>0</goal>
                <position>Forward</position>
                <discipline>
                    <red>0</red>
                    <yellow>0</yellow>
                </discipline>
            </player>
            <player ID="OD">
                <attack>
                    <dribble>0.7</dribble>
                    <pitching>1</pitching>
                    <cross>0.6</cross>
                    <shooting>0.4</shooting>
                    <header>0.3</header>
                    <freeKick>1</freeKick>
                </attack>
                <defense>
                    <broken>0.2</broken>
                    <interception>0.4</interception>
                    <clearance>0.3</clearance>
                    <forcedGrab>0.4</forcedGrab>
                    <headerClearance>0.2</headerClearance>
                    <GoalkeeperRescue>0</GoalkeeperRescue>
                </defense>
                <goal>2</goal>
                <position>Forward</position>
                <discipline>
                    <red>1</red>
                    <yellow>0</yellow>
                </discipline>
            </player>

            <player ID="NS">
                <attack>
                    <dribble>0.1</dribble>
                    <pitching>0.4</pitching>
                    <cross>0.5</cross>
                    <shooting>0.2</shooting>
                    <header>0</header>
                    <freeKick>0.2</freeKick>
                </attack>
                <defense>
                    <broken>0.8</broken>
                    <interception>0.6</interception>
                    <clearance>1</clearance>
                    <forcedGrab>0.3</forcedGrab>
                    <headerClearance>0.8</headerClearance>
                    <GoalkeeperRescue>0</GoalkeeperRescue>
                </defense>
                <goal>0</goal>
                <position>Defender</position>
                <discipline>
                    <red>0</red>
                    <yellow>1</yellow>
                </discipline>
            </player>
            <player ID="JA">
                <attack>
                    <dribble>0.2</dribble>
                    <pitching>0.3</pitching>
                    <cross>0.5</cross>
                    <shooting>0.3</shooting>
                    <header>0.2</header>
                    <freeKick>0.5</freeKick>
                </attack>
                <defense>
                    <broken>0.7</broken>
                    <interception>0.8</interception>
                    <clearance>0.6</clearance>
                    <forcedGrab>1</forcedGrab>
                    <headerClearance>0.9</headerClearance>
                    <GoalkeeperRescue>0</GoalkeeperRescue>
                </defense>
                <goal>1</goal>
                <position>Defender</position>
                <discipline>
                    <red>0</red>
                    <yellow>1</yellow>
                </discipline>
            </player>
            <player ID="GP">
                <attack>
                    <dribble>0.1</dribble>
                    <pitching>0.5</pitching>
                    <cross>0.2</cross>
                    <shooting>0.4</shooting>
                    <header>0.5</header>
                    <freeKick>0</freeKick>
                </attack>
                <defense>
                    <broken>0.6</broken>
                    <interception>0.8</interception>
                    <clearance>0.7</clearance>
                    <forcedGrab>0.5</forcedGrab>
                    <headerClearance>0.4</headerClearance>
                    <GoalkeeperRescue>0</GoalkeeperRescue>
                </defense>
                <goal>0</goal>
                <position>Defender</position>
                <discipline>
                    <red>0</red>
                    <yellow>1</yellow>
                </discipline>
            </player>
            <player ID="TV">
                <attack>
                    <dribble>0.2</dribble>
                    <pitching>0.1</pitching>
                    <cross>0.6</cross>
                    <shooting>0</shooting>
                    <header>0.6</header>
                    <freeKick>0.5</freeKick>
                </attack>
                <defense>
                    <broken>0.5</broken>
                    <interception>0.8</interception>
                    <clearance>0.8</clearance>
                    <forcedGrab>0.7</forcedGrab>
                    <headerClearance>0.4</headerClearance>
                    <GoalkeeperRescue>0</GoalkeeperRescue>
                </defense>
                <goal>0</goal>
                <position>Defender</position>
                <discipline>
                    <red>0</red>
                    <yellow>1</yellow>
                </discipline>
            </player>

            <player ID="IR">
                <attack>
                    <dribble>0.5</dribble>
                    <pitching>0.4</pitching>
                    <cross>0.6</cross>
                    <shooting>0.8</shooting>
                    <header>0.7</header>
                    <freeKick>0.4</freeKick>
                </attack>
                <defense>
                    <broken>0.5</broken>
                    <interception>0.3</interception>
                    <clearance>0.6</clearance>
                    <forcedGrab>1</forcedGrab>
                    <headerClearance>0.7</headerClearance>
                    <GoalkeeperRescue>0</GoalkeeperRescue>
                </defense>
                <goal>0</goal>
                <position>MidField</position>
                <discipline>
                    <red>0</red>
                    <yellow>1</yellow>
                </discipline>
            </player>
            <player ID="PC">
                <attack>
                    <dribble>0.4</dribble>
                    <pitching>0.2</pitching>
                    <cross>0.7</cross>
                    <shooting>0.4</shooting>
                    <header>0.6</header>
                    <freeKick>0.8</freeKick>
                </attack>
                <defense>
                    <broken>0.4</broken>
                    <interception>0.7</interception>
                    <clearance>0.9</clearance>
                    <forcedGrab>0.3</forcedGrab>
                    <headerClearance>1</headerClearance>
                    <GoalkeeperRescue>0</GoalkeeperRescue>
                </defense>
                <goal>1</goal>
                <position>MidField</position>
                <discipline>
                    <red>0</red>
                    <yellow>0</yellow>
                </discipline>
            </player>
            <player ID="SR">
                <attack>
                    <dribble>0.7</dribble>
                    <pitching>0.3</pitching>
                    <cross>0.2</cross>
                    <shooting>0.5</shooting>
                    <header>0.7</header>
                    <freeKick>0.9</freeKick>
                </attack>
                <defense>
                    <broken>0.3</broken>
                    <interception>0.7</interception>
                    <clearance>0.6</clearance>
                    <forcedGrab>0.5</forcedGrab>
                    <headerClearance>0.6</headerClearance>
                    <GoalkeeperRescue>0</GoalkeeperRescue>
                </defense>
                <goal>1</goal>
                <position>MidField</position>
                <discipline>
                    <red>0</red>
                    <yellow>1</yellow>
                </discipline>
            </player>


            <player ID="AOV">
                <attack>
                    <dribble>0</dribble>
                    <pitching>0</pitching>
                    <cross>0</cross>
                    <shooting>0</shooting>
                    <header>0</header>
                    <freeKick>0</freeKick>
                </attack>
                <defense>
                    <broken>0</broken>
                    <interception>0</interception>
                    <clearance>0</clearance>
                    <forcedGrab>0</forcedGrab>
